version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4.0.3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/ze-partners-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/ze-partners-api/dist/
      - ./package.json:/usr/src/ze-partners-api/package.json
    ports:
      - "1010:1010"
      - "9222:9222"
    links:
      - mongo